#define EGXMUTRIGGERS(ACTION, ...)                                   \
   ACTION(HLT_HIL1Mu3Eta2p5_EG10_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu3Eta2p5_EG15_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu3Eta2p5_EG20_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu3Eta2p5_EG30_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu5Eta2p5_EG10_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu5Eta2p5_EG15_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu5Eta2p5_EG20_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu5Eta2p5_EG30_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu7Eta2p5_EG10_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu7Eta2p5_EG15_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu7Eta2p5_EG20_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu7Eta2p5_EG30_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL1Mu12Eta2p5_EG10_v1, ## __VA_ARGS__)                \
   ACTION(HLT_HIL1Mu12Eta2p5_EG15_v1, ## __VA_ARGS__)                \
   ACTION(HLT_HIL1Mu12Eta2p5_EG20_v1, ## __VA_ARGS__)                \
   ACTION(HLT_HIL1Mu12Eta2p5_EG30_v1, ## __VA_ARGS__)                \
   ACTION(HLT_HIL1Mu3Eta2p5_EG10HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu3Eta2p5_EG15HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu3Eta2p5_EG20HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu3Eta2p5_EG30HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu5Eta2p5_EG10HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu5Eta2p5_EG15HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu5Eta2p5_EG20HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu5Eta2p5_EG30HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu7Eta2p5_EG10HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu7Eta2p5_EG15HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu7Eta2p5_EG20HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu7Eta2p5_EG30HECut_v1, ## __VA_ARGS__)            \
   ACTION(HLT_HIL1Mu12Eta2p5_EG10HECut_v1, ## __VA_ARGS__)           \
   ACTION(HLT_HIL1Mu12Eta2p5_EG15HECut_v1, ## __VA_ARGS__)           \
   ACTION(HLT_HIL1Mu12Eta2p5_EG20HECut_v1, ## __VA_ARGS__)           \
   ACTION(HLT_HIL1Mu12Eta2p5_EG30HECut_v1, ## __VA_ARGS__)           \
   ACTION(HLT_HIL2Mu3Eta2p5_EG10_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu3Eta2p5_EG15_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu3Eta2p5_EG20_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu3Eta2p5_EG30_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu5Eta2p5_EG10_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu5Eta2p5_EG15_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu5Eta2p5_EG20_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu5Eta2p5_EG30_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu7Eta2p5_EG10_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu7Eta2p5_EG15_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu7Eta2p5_EG20_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL2Mu7Eta2p5_EG30_v1, ## __VA_ARGS__)                 \
   ACTION(HLT_HIL3Mu3_EG10_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu3_EG15_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu3_EG20_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu3_EG30_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu5_EG10_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu5_EG15_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu5_EG20_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu5_EG30_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu7_EG10_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu7_EG15_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu7_EG20_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu7_EG30_v1, ## __VA_ARGS__)                       \
   ACTION(HLT_HIL3Mu3_EG10HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu3_EG15HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu3_EG20HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu3_EG30HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu5_EG10HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu5_EG15HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu5_EG20HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu5_EG30HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu7_EG10HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu7_EG15HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu7_EG20HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL3Mu7_EG30HECut_v1, ## __VA_ARGS__)                  \
   ACTION(HLT_HIL1Mu3Eta2p5_Ele10Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu3Eta2p5_Ele15Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu3Eta2p5_Ele20Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu5Eta2p5_Ele10Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu5Eta2p5_Ele15Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu5Eta2p5_Ele20Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu7Eta2p5_Ele10Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu7Eta2p5_Ele15Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL1Mu7Eta2p5_Ele20Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL2Mu3Eta2p5_Ele10Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL2Mu3Eta2p5_Ele15Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL2Mu3Eta2p5_Ele20Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL2Mu5Eta2p5_Ele10Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL2Mu5Eta2p5_Ele15Gsf_v1, ## __VA_ARGS__)             \
   ACTION(HLT_HIL2Mu5Eta2p5_Ele20Gsf_v1, ## __VA_ARGS__)
